-- Read the docs: https://www.lunarvim.org/docs/configuration
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/lunarvim/
-- Discord: https://discord.com/invite/Xb9B4Ny

require "opt"
require "user.mason"
require "user.lazy"
require "user.plugins"
require "user.builtin"
require "user.bufferline"
require "user.tabpage"
require "user.telescope"
require "user.nvimtree"
require "user.neotree"
require "user.lir"
require "user.config.enterleave"
require "user.config.cnoreabbrev"
require "user.config.plugins"
require "user.keymappings.LvimKey"
require "user.keymappings.whichkey"
require "user.keymappings.hydra"
require "user.keymappings.lsp"
require "user.session"
require "user.theme"
require "user.tabline"
require "user.copilot"
require "user.autocomplete"
require "user.treesitter"
require "user.integrated.vscode"
require "user.terminal"
require "user.lsp"
require "user.refactoring"
require "user.CodeRunner"
require "user.diagnostic"
require "user.trouble"
require "user.debug"
require "user.neotest"
